import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from '@nextui-org/react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-screen w-screen bg-black text-white" lang="en">
      <body className={`h-full w-full m-0 p-0 ${inter.className}`}>
        <NextUIProvider className="h-full w-full m-0 p-0">
            <main className="h-full w-full">{children}</main>
        </NextUIProvider>
      </body>
    </html>
  );
}
